{
 "title": "Montichat",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "New Monithchat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Web",
   "type": "stat",
   "description": "Status code site monitchat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox\", instance=\"https://new.monitchat.com/login\"}",
     "legendFormat": "Status Code"
    }
   ]
  },
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://api-v2.monitchat.com/\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Web Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(phase) (probe_http_duration_seconds{job=\"blackbox\", instance=\"https://new.monitchat.com/login\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(probe_http_duration_seconds{job=\"blackbox\", instance=\"https://new.monitchat.com/login\"})",
     "legendFormat": "TotalTime"
    }
   ]
  },
  {
   "title": "Mensagems Recebidas",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messages_received{job=\"MonitchatAPIV2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(phase) (probe_http_duration_seconds{job=\"blackbox\", instance=\"https://api-v2.monitchat.com/\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(probe_http_duration_seconds{job=\"blackbox\", instance=\"https://api-v2.monitchat.com/\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Numbers Conection",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitchat_whatsapp_active{job=\"MonitchatMonitor\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "API V4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox\", instance=\"https://api-v4.monitchat.com/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(phase) (probe_http_duration_seconds{instance=\"https://api-v4.monitchat.com/\", job=\"blackbox\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance) (probe_http_duration_seconds{instance=\"https://api-v4.monitchat.com/\", job=\"blackbox\"})",
     "legendFormat": "TotalTime"
    }
   ]
  }
 ]
}